Parish.create!([
  {name: "Buzzdog", in_charge: "Benjamin Sanchez", location: "Florida"},
  {name: "Eabox", in_charge: "Tammy Castillo", location: "Ohio"},
  {name: "Twimbo", in_charge: "Richard Carroll", location: "Florida"},
  {name: "Flipstorm", in_charge: "Martha Turner", location: "Arizona"},
  {name: "Eabox", in_charge: "Sara Williamson", location: "Ohio"},
  {name: "Trunyx", in_charge: "Alan Greene", location: "Indiana"},
  {name: "Riffpedia", in_charge: "Martha Elliott", location: "Michigan"},
  {name: "Jaloo", in_charge: "Ryan Nguyen", location: "California"},
  {name: "Meembee", in_charge: "Deborah Stevens", location: "Colorado"},
  {name: "Jabberstorm", in_charge: "Andrew Campbell", location: "Iowa"},
  {name: "Demizz", in_charge: "Debra Boyd", location: "District of Columbia"},
  {name: "Zava", in_charge: "Emily Carroll", location: "Rhode Island"},
  {name: "Kare", in_charge: "Steve Stephens", location: "Arizona"},
  {name: "Jaxworks", in_charge: "Wanda Kim", location: "Massachusetts"},
  {name: "Edgeclub", in_charge: "Philip Russell", location: "Colorado"},
  {name: "Devify", in_charge: "Dorothy Moreno", location: "New Mexico"}
])
Archdiocese.create!([
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
])
Deanery.create!([
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
])
Diocese.create!([
  {name: "Yombu", in_charge: "Doris Snyder"},
  {name: "Browsecat", in_charge: "Jonathan Oliver"},
  {name: "Wikibox", in_charge: "Pamela Montgomery"},
  {name: "Katz", in_charge: "Brandon Wilson"},
  {name: "Divavu", in_charge: "Julia Ortiz"},
  {name: "Devify", in_charge: "Rachel Martin"},
  {name: "Fivespan", in_charge: "Aaron Porter"},
  {name: "Topicshots", in_charge: "Nicole Chavez"},
  {name: "Centizu", in_charge: "Lori Wright"},
  {name: "Agimba", in_charge: "Aaron Woods"}
])
Member.create!([
  {name: "Donald Hicks"},
  {name: "Ronald Burton"},
  {name: "Theresa Jackson"},
  {name: "Melissa Warren"},
  {name: "Patricia Reynolds"},
  {name: "Eugene Fowler"},
  {name: "Peter Gutierrez"},
  {name: "Steve Marshall"},
  {name: "Teresa Fisher"},
  {name: "Janet Kelley"},
  {name: "Sara Peterson"},
  {name: "Kathryn Willis"},
  {name: "Wayne Anderson"},
  {name: "Dennis Austin"},
  {name: "Brandon Weaver"},
  {name: "Debra Meyer"},
  {name: "Carl Frazier"},
  {name: "Andrea Montgomery"},
  {name: "Jonathan Barnes"},
  {name: "Henry Hunt"},
  {name: "Matthew Roberts"},
  {name: "Christopher Willis"},
  {name: "Cheryl Thompson"},
  {name: "Sharon Simpson"},
  {name: "Harold Rodriguez"},
  {name: "Evelyn Morris"},
  {name: "Nicholas Franklin"},
  {name: "Sean Fuller"},
  {name: "Mary Allen"},
  {name: "Wayne Day"},
  {name: "Diana Fernandez"},
  {name: "Lori Taylor"},
  {name: "Doris Crawford"},
  {name: "Kevin Austin"},
  {name: "Justin Lawrence"},
  {name: "Keith Allen"},
  {name: "Keith Wagner"},
  {name: "Frances Elliott"},
  {name: "Charles Smith"},
  {name: "Douglas Ramos"},
  {name: "Joshua Martinez"},
  {name: "Dorothy King"},
  {name: "Brian Gordon"},
  {name: "Amanda Owens"},
  {name: "Philip Young"},
  {name: "Scott Webb"},
  {name: "Ryan Lopez"},
  {name: "George Hayes"},
  {name: "Peter Ramirez"},
  {name: "Andrew Arnold"},
  {name: "Michelle Castillo"},
  {name: "Clarence Simmons"},
  {name: "Willie Ford"},
  {name: "Thomas Franklin"},
  {name: "Ann Jordan"},
  {name: "Douglas Hicks"},
  {name: "Sara Woods"},
  {name: "Douglas Bennett"},
  {name: "Andrew Hicks"},
  {name: "Douglas Morales"},
  {name: "Janet Berry"},
  {name: "Susan Moreno"},
  {name: "Michelle Wagner"},
  {name: "Raymond Vasquez"},
  {name: "Evelyn Fox"},
  {name: "Todd Ford"},
  {name: "Scott Oliver"},
  {name: "Martha Riley"},
  {name: "Terry Flores"},
  {name: "Joyce Matthews"},
  {name: "Jose Perkins"},
  {name: "Deborah Castillo"},
  {name: "Sean Gordon"},
  {name: "Alice Daniels"},
  {name: "Joyce Kelley"},
  {name: "Martha Harris"},
  {name: "Kathy Tucker"},
  {name: "Jacqueline Freeman"},
  {name: "Julia Walker"},
  {name: "Jimmy Carroll"}
])
Parish.create!([
  {name: "Buzzdog", in_charge: "Benjamin Sanchez", location: "Florida"},
  {name: "Eabox", in_charge: "Tammy Castillo", location: "Ohio"},
  {name: "Twimbo", in_charge: "Richard Carroll", location: "Florida"},
  {name: "Flipstorm", in_charge: "Martha Turner", location: "Arizona"},
  {name: "Eabox", in_charge: "Sara Williamson", location: "Ohio"},
  {name: "Trunyx", in_charge: "Alan Greene", location: "Indiana"},
  {name: "Riffpedia", in_charge: "Martha Elliott", location: "Michigan"},
  {name: "Jaloo", in_charge: "Ryan Nguyen", location: "California"},
  {name: "Meembee", in_charge: "Deborah Stevens", location: "Colorado"},
  {name: "Jabberstorm", in_charge: "Andrew Campbell", location: "Iowa"},
  {name: "Demizz", in_charge: "Debra Boyd", location: "District of Columbia"},
  {name: "Zava", in_charge: "Emily Carroll", location: "Rhode Island"},
  {name: "Kare", in_charge: "Steve Stephens", location: "Arizona"},
  {name: "Jaxworks", in_charge: "Wanda Kim", location: "Massachusetts"},
  {name: "Edgeclub", in_charge: "Philip Russell", location: "Colorado"},
  {name: "Devify", in_charge: "Dorothy Moreno", location: "New Mexico"}
])
Service.create!([
  {name: "massa", content: "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.", tags: "sapien arcu sed augue aliquam erat", date: "2014-12-15 14:48:59", parish_id: 1},
  {name: "curae", content: "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.", tags: "arcu adipiscing molestie hendrerit at vulputate", date: "2015-02-26 20:26:37", parish_id: 2},
  {name: "fusce", content: "Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.", tags: "ligula suspendisse ornare consequat", date: "2014-07-15 02:57:50", parish_id: 3},
  {name: "justo", content: "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.", tags: "nisi eu orci mauris", date: "2014-06-29 13:14:08", parish_id: 4},
  {name: "aliquet", content: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.", tags: "massa volutpat convallis morbi odio odio", date: "2014-08-26 11:28:03", parish_id: 5},
  {name: "pretium", content: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.", tags: "vivamus in felis eu sapien cursus", date: "2015-05-30 10:03:09", parish_id: 6},
  {name: "nisi", content: "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.", tags: "est phasellus sit amet erat", date: "2014-06-30 01:13:15", parish_id: 7},
  {name: "nullam", content: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.", tags: "mus vivamus vestibulum sagittis sapien cum", date: "2014-08-29 02:41:51", parish_id: 8},
  {name: "justo", content: "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.", tags: "sapien urna pretium nisl ut", date: "2014-12-25 23:38:07", parish_id: 9},
  {name: "quisque", content: "Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.", tags: "massa quis augue luctus tincidunt nulla", date: "2015-01-05 17:03:18", parish_id: 10},
  {name: "rhoncus", content: "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.", tags: "ut tellus nulla ut", date: "2014-10-26 21:07:13", parish_id: 11},
  {name: "justo", content: "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", tags: "augue vestibulum rutrum rutrum neque", date: "2015-01-20 20:38:31", parish_id: 12},
  {name: "nulla", content: "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.", tags: "euismod scelerisque quam turpis", date: "2014-06-25 06:27:46", parish_id: 13},
  {name: "condimentum", content: "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.", tags: "suspendisse accumsan tortor quis turpis sed", date: "2015-03-30 00:20:27", parish_id: 14},
  {name: "dapibus", content: "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.", tags: "risus auctor sed tristique in tempus", date: "2014-12-12 05:14:46", parish_id: 15},
  {name: "convallis", content: "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", tags: "luctus cum sociis natoque", date: "2015-05-24 10:44:45", parish_id: 16}
])
User.create!([
  {email: "admin@senshi.com", password: "12345678", uid:"admin@senshi.com", provider:"email", confirmed_at:"2015-06-24 19:23:58", confirmation_sent_at:"2015-06-24 16:21:27"}
])